### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'img_size'

### ISSUE THREAD

**Issue by liwenchao0615** [hdnh2006/YOLOv8API#2]
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\yolov8my\lib\site-packages\werkzeug\wsgi.py", line 289, in __next__
    return self._next()
  File "C:\Users\Administrator\anaconda3\envs\yolov8my\lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
  File "C:\Users\Administrator\anaconda3\envs\yolov8my\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "F:\projectprogram\comparison_experiment\ZERRIDNet-comparision\YOLOv8API-main\detect_api.py", line 117, in detect
    dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
TypeError: __init__() got an unexpected keyword argument 'img_size'

**Comment by hdnh2006** [comment]
Sorry for the late reply, I will check it as soon as possible

**Comment by hdnh2006** [comment]
As I explained in https://github.com/hdnh2006/YOLOv8API/issues/1:

I need to update the API but running 'pip install 'ultralytics==8.0.134' should solve the problem.

Requirements has been updated, try again.

**Comment by hdnh2006** [comment]
Hello! new format of `ultralytics` packages has been added and all the tasks are now supported in the same API, please check and let me know any issue!
